#!/usr/bin/env bash
# Installs nginx and configures a custom HTTP response header

apt-get update -y
apt-get install -y nginx

# add custom header inside the server block
sed -i '/server_name _;/a \    add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# restart nginx
service nginx restart
