#!/usr/bin/env bash
# Configures Nginx to have a custom 404 page

# Update and install Nginx
apt-get update -y
apt-get install -y nginx

# Create index page
echo 'Holberton School for the win!' > /var/www/html/index.nginx-debian.html

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx with redirect and custom 404
cat > /etc/nginx/sites-available/default << 'EOF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.nginx-debian.html index.html index.htm;

    server_name _;

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

# Test Nginx configuration
nginx -t

# Restart Nginx
service nginx restart